version: '3'
services:
  nginx:
    image: nginx:latest
    restart:
      always
    ports:
     - "9010:3000"
    volumes:
     - ./nginx/conf.d:/etc/nginx/conf.d
     - ./nginx/build:/usr/share/nginx/html
    command: /bin/bash -c "nginx -g 'daemon off;'"